BMNC/urls.py
from django.contrib import admin
from django.conf.urls import url, include
import bmnc_news.urls as bmnc_news
import bmnc_sign_up.urls as bmnc_sign_up
import bmnc_polling.urls as bmnc_polling
import bmnc_profile.urls as bmnc_profile
from django.views.generic.base import RedirectView

urlpatterns = [
    url('admin/', admin.site.urls),
    url(r'^news/', include(bmnc_news,namespace='bmnc-news')),
    url(r'^home/', include(bmnc_sign_up,namespace='bmnc-home')),
    url(r'^polling/', include(bmnc_polling, namespace='bmnc-polling')),
    url(r'^profile/', include(bmnc_polling, namespace='bmnc-profile')),
    url(r'^$', RedirectView.as_view(url="/home/", permanent='true'),name='index')
]

bmnc_news/urls.py
from django.conf.urls import url
from .views import index

urlpatterns = [
    url(r'^$', index, name='index'),
]

bmnc_news/models.py
from django.db import models, connection

# Create your models here.

bmnc_news/views.py
from django.shortcuts import render

response = {'author': 'BMNC14B'}
    
def index(request):
	html = 'bmnc_news/news.html'	
	print('ke berita')
	return render(request, html, response)

bmnc_news/templates/bmnc_news/partials/footer.html
<p>Made by BMNCB14</p>
<p>&copy; Made with Love</p>

bmnc_news/templates/bmnc_news/partials/header.html
<nav class="navbar navbar-expand-md bg-primary navbar-dark">
  <div class="container-fluid">
    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbar2SupportedContent">
      <span class="navbar-toggler-icon"></span>
    </button>
    <a class="navbar-brand" href="{% url 'bmnc-news:index' %}">
      <img src="https://i.imgur.com/YBdO41f.png" alt="Commercial Photography" width="150"> </a>
    <div class="collapse navbar-collapse text-center justify-content-end" id="navbar2SupportedContent">
      <ul class="navbar-nav text-light text-center">
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light"data-toggle="modal" data-target=".bs-example-modal-sm"style="font-family:Raleway">Logout</a>
          <div class="modal bs-example-modal-sm" tabindex="-1" role="dialog" aria-hidden="true">
            <div class="modal-dialog modal-sm">
              <div class="modal-content">
                <div class="modal-header"><h4>Logout <i class="fa fa-lock"></i></h4>
                  <button type="button" class="close" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button></div>
                <div class="modal-body"><i class="fa fa-question-circle"></i> Are you sure you want to log-off?</div>
                <div class="modal-footer"><a href="" class="btn btn-primary btn-block">Logout</a></div>
              </div>
            </div>
</div>
        </li>
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light" id ="history" a href="{% url 'bmnc-polling:index' %}" style="font-family:Raleway">rio_kurtinus</a>
        </li>
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light" id ="news"a href="{% url 'bmnc-news:index' %}" style="font-family:Raleway">Berita</a>
        </li>
        <li class="nav-item text-center text-light">
          <a class="nav-link text-light" id ="user" href="{% url 'bmnc-profile:index' %}" style="font-family:Raleway">Polling</a>
        </li>
      </ul>